name: Release

on:
  push:
    tags: [v*.*.*]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: deploy
        run: |
          npm ci
          npm run deploy -- --require-approval never --progress events
        env:
          SNS_EMAIL: ${{ secrets.SNS_EMAIL }}
      
      - name: Create release
        id: create-release
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref.replace('refs/tags/', ''),
              target_commitish: context.sha,
              name: context.ref.replace('refs/tags/', ''),
              draft: false,
              prerelease: false,
              generate_release_notes: true,
            });